import hamburger from "./Images/Hamburger2.jpg";

export const tags = ["asain", "pasta", "beef", "chicken", "soups", "baking"];

export const recipesArr = [
  {
    name: "Hamburger",
    id: "1",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "30 min",
    CoockTime: "30 min",
    Tag: ["Beef", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Pasta",
    id: "2",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "15 min",
    CoockTime: "20 min",
    Tag: ["Pasta", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Soup",
    id: "3",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "10 min",
    CoockTime: "15 min",
    Tag: ["soup", "dinner", "supper"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Hamburger",
    id: "4",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "30 min",
    CoockTime: "30 min",
    Tag: ["Beef", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Hamburger",
    id: "5",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "30 min",
    CoockTime: "30 min",
    Tag: ["Beef", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Hamburger",
    id: "6",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "30 min",
    CoockTime: "30 min",
    Tag: ["Beef", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Hamburger",
    id: "7",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "30 min",
    CoockTime: "30 min",
    Tag: ["Beef", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Pasta",
    id: "8",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "15 min",
    CoockTime: "20 min",
    Tag: ["Pasta", "dinner"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
  {
    name: "Soup",
    id: "9",
    details:
      "A classic homemade hamburger is a juicy, flavorful beef patty served on a toasted bun with an array of toppings. The patty is usually seasoned with salt and pepper and cooked to your desired level of doneness, giving it a tender and moist texture. The bun provides a soft and slightly sweet base, while toppings such as lettuce, tomato, onion, cheese, and condiments add crunch, freshness, and tanginess to the burger. Overall, a homemade hamburger is a simple yet delicious meal that satisfies the taste buds and the stomach.",
    img: hamburger,
    ingrediants: [
      "Ground beef",
      "Pepper",
      "Hamburger buns",
      "Lettuce",
      "Tomato",
      "Onion",
      "Condiments (ketchup, mustard, mayo)",
    ],
    description:
      "Juicy beef patty seasoned with salt and pepper, cooked to desired doneness, and served on a toasted bun with your favorite toppings.",
    prepTime: "10 min",
    CoockTime: "15 min",
    Tag: ["soup", "dinner", "supper"],
    instructions: [
      "Mix ground beef with salt and pepper.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 3-5 minutes on each side, or until they reach your desired level of doneness.",
      "Toast the hamburger buns on the grill or in a toaster oven.",
      "Assemble the burger by placing lettuce, tomato, and onion on the bottom bun, followed by the cooked patty and a slice of cheese.",
      "Add condiments to the top bun and place it on top of the burger.,",
      "Serve and enjoy!",
    ],
  },
];
